//USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//USER LOGOUT
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

// FETCH USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'CREATE_USERS_FAIL';

//EMPLOYEES

export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_FAIL = 'CREATE_EMPLOYEE_FAIL';

// FETCH EMPLOYEES
export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAIL = 'CREATE_EMPLOYEE_FAIL';

//DELETE EMPLOYEES
export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL';

//EMPLOYEE DETAILS
export const EMPLOYEE_DETAIL_REQUEST = 'EMPLOYEE_DETAIL_REQUEST';
export const EMPLOYEE_DETAIL_SUCCESS = 'EMPLOYEE_DETAIL_SUCCESS';
export const EMPLOYEE_DETAIL_FAIL = 'EMPLOYEE_DETAIL_FAIL';

//UPDATE EMPLOYEES
export const EMPLOYEE_UPDATE_REQUEST = 'EMPLOYEE_UPDATE_REQUEST';
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS';
export const EMPLOYEE_UPDATE_FAIL = 'EMPLOYEE_UPDATE_FAIL';



//LEAVE

export const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST';
export const CREATE_LEAVE_SUCCESS = 'CREATE_LEAVE_SUCCESS';
export const CREATE_LEAVE_FAIL = 'CREATE_LEAVE_FAIL';

// FETCH LEAVE
export const FETCH_LEAVE_REQUEST = 'FETCH_LEAVE_REQUEST';
export const FETCH_LEAVE_SUCCESS = 'FETCH_LEAVE_SUCCESS';
export const FETCH_LEAVE_FAIL = 'CREATE_LEAVE_FAIL';

//DELETE LEAVE
export const DELETE_LEAVE_REQUEST = 'DELETE_LEAVE_REQUEST';
export const DELETE_LEAVE_SUCCESS = 'DELETE_LEAVE_SUCCESS';
export const DELETE_LEAVE_FAIL = 'DELETE_LEAVE_FAIL';

//LEAVE DETAILS
export const LEAVE_DETAIL_REQUEST = 'LEAVE_DETAIL_REQUEST';
export const LEAVE_DETAIL_SUCCESS = 'LEAVE_DETAIL_SUCCESS';
export const LEAVE_DETAIL_FAIL = 'LEAVE_DETAIL_FAIL';